#+title: Spotify Data Parser Dev Log
#+author:  Donald Khek

* Project Goals
- [ ] Create a python script that reads user's JSON files and outputs their most played song and artist with the number of minutes (basic start)
- [ ] Create a website using flask to display the user's Spotify data in a more /human/ way
  - [ ] Showcase user's data using graphs possibly
  - [ ] Could take on a style similar to last.fm where it displays when you played a song
- [ ] Experiment with Machine Learning
  - [ ] Possibly to predict the next song the user will play or if they will skip a song
* Journal
** 2025-02-05: Creating the Basic Script
:PROPERTIES:
:CREATED: <2026-02-05 Thu 22:59> 
:END:
Today is the day the project actually begins. Honestly, the biggest hurdle today was familiarizing myself with Python after coding primarily in C++ and JS before. I was able to create a script that read all of my spotify data and listed the amount of times it was played.

The only issue is that it takes a while to read all the data, so I'll have to find a better database system or experiment with a smaller sample size, probably both.
